# Generated by Django 3.2.14 on 2023-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_remove_paciente_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.TextField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de obra social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='altura_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura [m]'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='baja',
            field=models.BooleanField(default=False, verbose_name='Baja'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numeroObraSocial',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº de obra social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso [kg]'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
    ]
