# Generated by Django 3.2.14 on 2023-07-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20230727_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], default='m', max_length=1, verbose_name='Sexo'),
        ),
    ]
