# Generated by Django 3.2.14 on 2023-07-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
    ]
