# Generated by Django 3.2.14 on 2023-08-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['dni']},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obraSocial',
            field=models.ForeignKey(default='A completar', on_delete=django.db.models.deletion.CASCADE, to='paciente.obrasocial', verbose_name='Obra Social'),
        ),
    ]
