# Generated by Django 3.2.14 on 2023-08-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_alter_paciente_obrasocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obraSocial',
            field=models.ForeignKey(default='A completar', on_delete=django.db.models.deletion.CASCADE, to='paciente.obrasocial', verbose_name='Obra Social'),
        ),
    ]
