# Generated by Django 3.2.14 on 2023-08-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_auto_20230803_1022'),
        ('paciente', '0013_alter_paciente_obrasocial'),
    ]

    operations = [
    ]
