# Generated by Django 3.2.14 on 2023-08-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_paciente_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='usuarios-perfil/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('', '--- Seleccione ---'), ('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
    ]
