# Generated by Django 3.2.14 on 2023-08-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_merge_20230804_1520'),
        ('paciente', '0016_auto_20230807_0953'),
    ]

    operations = [
    ]
