# Generated by Django 3.2.14 on 2023-08-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_delete_pacienterealizaencuesta'),
        ('paciente', '0016_auto_20230807_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteRealizaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('', '--- Seleccione ---'), ('b', 'borrador'), ('p', 'publicado')], default='b', max_length=1)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.form')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='encuestas',
            field=models.ManyToManyField(through='paciente.PacienteRealizaEncuesta', to='index.Form'),
        ),
    ]
