# Generated by Django 3.2.14 on 2023-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_auto_20230809_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienterealizaencuesta',
            name='estado',
            field=models.CharField(choices=[('', '--- Seleccione ---'), ('b', 'borrador'), ('p', 'publicada')], default='b', max_length=1),
        ),
    ]
