# Generated by Django 3.2.14 on 2023-08-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_merge_20230812_1313'),
        ('paciente', '0018_alter_pacienterealizaencuesta_estado'),
    ]

    operations = [
    ]
