# Generated by Django 3.2.14 on 2023-08-13 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0020_auto_20230813_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacienterealizaencuesta',
            old_name='fecha',
            new_name='fechaModificacion',
        ),
        migrations.AddField(
            model_name='pacienterealizaencuesta',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
