# Generated by Django 3.2.14 on 2023-07-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('f', 'femenino'), ('m', 'masculino'), ('o', 'otro')], max_length=1, verbose_name='sexo')),
                ('dni', models.IntegerField(verbose_name='dni')),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='direccion')),
                ('telefono', models.TextField(blank=True, max_length=30, null=True, verbose_name='telefono')),
                ('tipo_usuario', models.CharField(choices=[('p', 'paciente'), ('m', 'medico'), ('a', 'administrador')], max_length=1, verbose_name='tipo de usuario')),
                ('matricula', models.IntegerField(blank=True, null=True, verbose_name='matricula')),
                ('especialidad', models.TextField(max_length=100, verbose_name='especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
