# Generated by Django 3.2.14 on 2023-07-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_remove_medico_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('nombre', models.TextField(max_length=100, primary_key=True, serialize=False, verbose_name='Especialidad')),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.especialidad'),
        ),
    ]
