# Generated by Django 3.2.14 on 2023-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_auto_20230727_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
