# Generated by Django 3.2.14 on 2023-07-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_alter_medico_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('-', 'A completar'), ('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], default='-', max_length=1, verbose_name='Sexo'),
        ),
    ]
