# Generated by Django 3.2.14 on 2023-07-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_alter_medico_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
    ]
