# Generated by Django 3.2.14 on 2023-07-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0007_alter_medico_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(default='A completar', on_delete=django.db.models.deletion.CASCADE, to='medico.especialidad'),
        ),
    ]
