# Generated by Django 3.2.14 on 2023-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_auto_20230727_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['dni']},
        ),
        migrations.AlterField(
            model_name='medico',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='DNI'),
        ),
    ]
