# Generated by Django 3.2.14 on 2023-08-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0009_auto_20230803_1022'),
        ('medico', '0010_auto_20230803_0940'),
    ]

    operations = [
    ]

# Generated by Django 3.2.14 on 2023-08-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0009_auto_20230803_1022'),
        ('medico', '0010_auto_20230803_0940'),
    ]

    operations = [
    ]
