# Generated by Django 3.2.14 on 2023-08-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0012_auto_20230804_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='usuarios-perfil/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('', '--- Seleccione ---'), ('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro')], max_length=1, verbose_name='Sexo'),
        ),
    ]
