# Generated by Django 3.2.14 on 2023-08-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0014_auto_20230807_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='fechaAlta',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
    ]
