# Generated by Django 3.2.14 on 2023-08-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0016_auto_20230808_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='medicocreaencuesta',
            options={'verbose_name': 'Medico Crea Encuesta', 'verbose_name_plural': 'Medicos Crean Encuestas'},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
    ]
