# Generated by Django 4.0.2 on 2023-05-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_answer_id_alter_choices_id_alter_form_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Se ha guardado tu respuesta', max_length=10000),
        ),
    ]
