# Generated by Django 4.0.2 on 2023-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_form_confirmation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='background_color',
            field=models.CharField(default='#f2f6fc', max_length=20),
        ),
    ]
