# Generated by Django 4.0.2 on 2023-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_form_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Se ha guardado su respuesta', max_length=10000),
        ),
    ]
