# Generated by Django 3.2.14 on 2023-08-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='state',
            field=models.CharField(choices=[('', '--- Seleccione ---'), ('b', 'borrador'), ('p', 'publicado')], default='b', max_length=1),
        ),
    ]
