# Generated by Django 3.2.14 on 2023-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20230808_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='state',
            new_name='status',
        ),
    ]
