# Generated by Django 3.2.14 on 2023-08-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_state_form_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacienteRealizaEncuesta',
        ),
    ]
