# Generated by Django 3.2.14 on 2023-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_delete_pacienterealizaencuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('', '--- Seleccione ---'), ('b', 'borrador'), ('p', 'publicada')], default='b', max_length=1),
        ),
    ]
