# Generated by Django 3.2.14 on 2023-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_form_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name': 'Opción', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Encuesta', 'verbose_name_plural': 'Encuestas'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='responses',
            options={'verbose_name': 'Responde Respuesta', 'verbose_name_plural': 'Responden Respuestas'},
        ),
        migrations.AlterField(
            model_name='form',
            name='authenticated_responder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Sus respuestas han sido guardadas con éxito!', max_length=10000),
        ),
    ]
