name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - develop
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY_DEV }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile.dev
          tags:  ${{ env.DOCKERHUB_USERNAME }}/pfsatdev:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > pfsat.pem
        chmod 600 pfsat.pem
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i pfsat.pem ec2-user@ec2-15-228-73-227.sa-east-1.compute.amazonaws.com 'sudo docker pull ${{ env.DOCKERHUB_USERNAME }}/pfsatdev:latest'
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i pfsat.pem ec2-user@ec2-15-228-73-227.sa-east-1.compute.amazonaws.com 'sudo docker stop pfsatdev || true'
        ssh -o StrictHostKeyChecking=no -i pfsat.pem ec2-user@ec2-15-228-73-227.sa-east-1.compute.amazonaws.com 'sudo docker rm pfsatdev || true'
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i pfsat.pem ec2-user@ec2-15-228-73-227.sa-east-1.compute.amazonaws.com 'sudo docker run -d --name pfsatdev -p 80:8000 ${{ env.DOCKERHUB_USERNAME }}/pfsatdev:latest'